//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 04:52:56 AM EET 
//


package org.itroi.user;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.itroi.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _User_QNAME = new QName("http://www.itroi.org/user", "user");
    private final static QName _UserTypeMemberOfGroups_QNAME = new QName("http://www.itroi.org/user", "memberOfGroups");
    private final static QName _UserTypeName_QNAME = new QName("http://www.itroi.org/user", "name");
    private final static QName _UserTypeEmail_QNAME = new QName("http://www.itroi.org/user", "email");
    private final static QName _UserTypeLogin_QNAME = new QName("http://www.itroi.org/user", "login");
    private final static QName _UserTypePassword_QNAME = new QName("http://www.itroi.org/user", "password");
    private final static QName _UserTypeSurname_QNAME = new QName("http://www.itroi.org/user", "surname");
    private final static QName _UserTypeGender_QNAME = new QName("http://www.itroi.org/user", "gender");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.itroi.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link MemberOfGroup }
     * 
     */
    public MemberOfGroup createMemberOfGroup() {
        return new MemberOfGroup();
    }

    /**
     * Create an instance of {@link MemberOfGroups }
     * 
     */
    public MemberOfGroups createMemberOfGroups() {
        return new MemberOfGroups();
    }

    /**
     * Create an instance of {@link GroupRole }
     * 
     */
    public GroupRole createGroupRole() {
        return new GroupRole();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.itroi.org/user", name = "user")
    public JAXBElement<UserType> createUser(UserType value) {
        return new JAXBElement<UserType>(_User_QNAME, UserType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MemberOfGroups }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.itroi.org/user", name = "memberOfGroups", scope = UserType.class)
    public JAXBElement<MemberOfGroups> createUserTypeMemberOfGroups(MemberOfGroups value) {
        return new JAXBElement<MemberOfGroups>(_UserTypeMemberOfGroups_QNAME, MemberOfGroups.class, UserType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.itroi.org/user", name = "name", scope = UserType.class)
    public JAXBElement<String> createUserTypeName(String value) {
        return new JAXBElement<String>(_UserTypeName_QNAME, String.class, UserType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.itroi.org/user", name = "email", scope = UserType.class)
    public JAXBElement<String> createUserTypeEmail(String value) {
        return new JAXBElement<String>(_UserTypeEmail_QNAME, String.class, UserType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.itroi.org/user", name = "login", scope = UserType.class)
    public JAXBElement<String> createUserTypeLogin(String value) {
        return new JAXBElement<String>(_UserTypeLogin_QNAME, String.class, UserType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.itroi.org/user", name = "password", scope = UserType.class)
    public JAXBElement<String> createUserTypePassword(String value) {
        return new JAXBElement<String>(_UserTypePassword_QNAME, String.class, UserType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.itroi.org/user", name = "surname", scope = UserType.class)
    public JAXBElement<String> createUserTypeSurname(String value) {
        return new JAXBElement<String>(_UserTypeSurname_QNAME, String.class, UserType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.itroi.org/user", name = "gender", scope = UserType.class)
    public JAXBElement<String> createUserTypeGender(String value) {
        return new JAXBElement<String>(_UserTypeGender_QNAME, String.class, UserType.class, value);
    }

}
